export default {
  adult: false,
  backdrop_path: "/v4yVTbbl8dE1UP2dWu5CLyaXOku.jpg",
  belongs_to_collection: null,
  budget: 183000000,
  genres: [],
  homepage: null,
  id: 420817,
  imdb_id: "tt6139732",
  original_language: "en",
  original_title: "Aladdin",
  overview: "A kindhearted street urchin named Aladdin embarks on a magical adventure after finding a lamp that releases a wisecracking genie while a power-hungry Grand Vizier vies for the same lamp that has the power to make their deepest wishes come true.",
  popularity: 559.104,
  poster_path: "/3iYQTLGoy7QnjcUYRJy4YrAgGvp.jpg",
  production_companies: [],
  production_countries: [],
  release_date: "2019-05-22",
  revenue: 0,
  runtime: 128,
  spoken_languages: [],
  status: "Released",
  tagline: "Choose Wisely.",
  title: "Aladdin",
  video: false,
  vote_average: 7.2,
  vote_count: 463
}